name: opq-dev

### Appends to Helm values ###
values: 
  cluster_app_values: |
    awsRegion: ap-south-1
    autoDiscovery:
      clusterName: opq-dev
      tag: "k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/opq-dev"
    rbac:
      serviceAccount:
        create: true
        name: "cluster-autoscaler"
        annotations:
          eks.amazonaws.com/role-arn: "arn:aws:iam::891543987898:role/cluster-autoscaler-opq-dev"
    extraArgs:
      skip-nodes-with-local-storage: false
      scale-down-utilization-threshold: 0.9
