apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: external-secrets
  namespace: argocd
spec:
  sourceRepos:
  - https://github.com/mlkrtk/argocd-bootstrapping.git
  - https://charts.external-secrets.io
  destinations:
  - server: "*"
    namespace: "*"
  - server: https://kubernetes.default.svc
    namespace: argocd
  description: External secrets
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"
  roles:
