apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: addon-base-root
  namespace: argocd
spec:
  sourceRepos:
  - https://github.com/mlkrtk/argocd-bootstrapping.git
  destinations:
  - server: https://kubernetes.default.svc
    namespace: argocd
  description: Addon base root
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"